credentials:
  usernames:
    admin:
      email: admin@arkeos.com
      name: Administrateur
      password: 'MADLAL19791979'
cookie:
  expiry_days: 30
  key: arkeos_secret_key_2026
  name: arkeos_auth
preauthorized:
  emails:
    - tech@arkeos.com
